<a href="https://colab.research.google.com/github/narelaarmani/dm2026a/blob/main/494_tareahogar_04_exp3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tarea para el Hogar 05

##  1. Overfitting the Public Leaderboard

Leer  https://medium.com/hmif-itb/overfitting-the-leaderboard-da25172ac62e
( 8 minutos )

## 2. Hiperparámetros del LightGBM

Los objetivos de esta tarea son:


*   Aumentar la rentabilidad de la campaña de marketing de retención proactiva de clientes.
*   Generar un mejor modelo optimizando sus hiperparámetros
*   Conceptual : investigar los mas relevantes hiperparámetros de LightGBM
*   Familiarizarse con el uso de máquinas virtuales de Google Colab
*   Ver un pipeline completo de optimización de hiperparámetros y puesta en producción

LightGBM cuenta con mas de 60 hiperparámetros, siendo posible utilizar 40 al mismo tiempo, aunque no razonable.
<br> La documentación oficial de los hiperparámetros de LightGBM es  https://lightgbm.readthedocs.io/en/latest/Parameters.html#core-parameters

Se lo alerta sobre que una Optimizacion sw Hiperparámetros lleva varias horas de corrida, y usted deberá correr VARIAS optimizaciones para descubrir cuales parámetros conviene optimizar.

Es necesario investigar cuales son los hiperparámetros de LightGBM que vale la pena optimizar, ya que los realmente utiles son apenas un reducido subconjunto.
<br>Usted deberá investigar cuales son los hiperparámetros mas relevantes de LightGBM, su primer alternativa es preguntándole a su amigo con capacidades especiales ChatGPT o sus endogámicos familiares Claude, DeepSeek, Gemini, Grok, etc
<br> La segunda alternativa es la propia documentación de LightGBM  https://lightgbm.readthedocs.io/en/latest/Parameters-Tuning.html

Adicionalmente podra buscar información como la que proveen esta diminuta muestra aleatoria de artículos ligeros:
* https://machinelearningmastery.com/light-gradient-boosted-machine-lightgbm-ensemble/
*  https://medium.com/@sarahzouinina/a-deep-dive-into-lightgbm-how-to-choose-and-tune-parameters-7c584945842e
*  https://www.kaggle.com/code/somang1418/tuning-hyperparameters-under-10-minutes-lgbm
*  https://towardsdatascience.com/beginners-guide-to-the-must-know-lightgbm-hyperparameters-a0005a812702/


<br>  La muestra anterior se brinda a modo de ejemplo, usted deberá buscar muuuuchas  fuentes adicionales de información
<br> Tenga presente que LightGBM es el estado del arte en modelado predictivo para datasets estructurado, que son el 90% del trabajo del 95% de los Data Scientists en Argentina.

El desafío de esta tarea es:
* Qué hiperparparámetros conviene optimizar?  Las recomendaciones de los artículos ligeros es siempre sensata?  Sus autores realmente hicieron experimentos o son siemplemente escritores de entretenimiento carente de base científica?
* Elegidos los hiperparámetros, cual es el  <desde, hasta> que se debe utilizar en la Bayesian Optimization ?
* Realmente vale la pena optimizar 10 o 16 hiperparámetros al mismo tiempo ?  No resulta contraproducente una búsqueda en un espacio de tal alta dimensionalidad ?

#### 2.1  Seteo del ambiente en Google Colab

Esta parte se debe correr con el runtime en Python3
<br>Ir al menu, Runtime -> Change Runtime Type -> Runtime type ->  **Python 3**

Conectar la virtual machine donde esta corriendo Google Colab con el  Google Drive, para poder tener persistencia de archivos

In [ ]:
# primero establecer el Runtime de Python 3
from google.colab import drive
drive.mount('/content/.drive')

Mounted at /content/.drive

Para correr la siguiente celda es fundamental en Arranque en Frio haber copiado el archivo kaggle.json al Google Drive, en la carpeta indicada en el instructivo

<br>los siguientes comando estan en shell script de Linux
*   Crear las carpetas en el Google Drive
*   "instalar" el archivo kaggle.json desde el Google Drive a la virtual machine para que pueda ser utilizado por la libreria  kaggle de Python
*   Bajar el  **dataset_pequeno**  al  Google Drive  y tambien al disco local de la virtual machine que esta corriendo Google Colab

In [ ]:
%%shell

mkdir -p "/content/.drive/My Drive/dm"
mkdir -p "/content/buckets"
ln -sfn "/content/.drive/My Drive/dm"   /content/buckets/b1

mkdir -p ~/.kaggle
cp /content/buckets/b1/kaggle/kaggle.json  ~/.kaggle
chmod 600 ~/.kaggle/kaggle.json


mkdir -p /content/buckets/b1/exp
mkdir -p /content/buckets/b1/datasets
mkdir -p /content/datasets


# defino funcion descargar()
descargar() {
  carpeta_destino="/content/buckets/b1/datasets/"
  url_origen="https://storage.googleapis.com/open-courses/itba2026-7c9a/dm/"
  archivo="$1"

  if ! test -f "$carpeta_destino""$archivo"; then
    wget  "$url_origen""$archivo"  -O "$carpeta_destino""$archivo"
  fi

  if ! test -f  "/content/datasets/""$archivo"; then
    cp  "$carpeta_destino""$archivo"  "/content/datasets/""$archivo"
  fi;
}


# hago la descarga efectiva, llamando a descargar()
descargar  "dataset_pequeno.csv"

### 2.2 Optimizacion Hiperparámetros

Esta parte se debe correr con el runtime en lenguaje R Ir al menu, Runtime -> Change Runtime Type -> Runtime type -> R

### 2.2.1 Inicio

limpio el ambiente de R

In [ ]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Wed Jun 24 10:39:00 PM 2026"

In [ ]:
# limpio la memoria
rm(list=ls(all.names=TRUE)) # remove all objects
gc(full=TRUE, verbose=FALSE) # garbage collection

       used    (Mb) gc trigger (Mb) max used (Mb)
Ncells  671246 35.9 1473245    78.7 1473245  78.7
Vcells 1242595  9.5 8388608    64.0 1978677  15.1

### 2.2.2 Carga de Librerias

In [ ]:
# cargo las librerias que necesito
require("data.table")
require("parallel")

if( !require("primes") ) install.packages("primes")
require("primes")

if( !require("utils") ) install.packages("utils")
require("utils")

if( !require("rlist") ) install.packages("rlist")
require("rlist")

if( !require("yaml")) install.packages("yaml")
require("yaml")

if( !require("lightgbm") ) install.packages("lightgbm")
require("lightgbm")

Loading required package: data.table


Attaching package: ‘data.table’


The following object is masked from ‘package:base’:

    %notin%


Loading required package: parallel

Loading required package: primes

Warning message in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :
“there is no package called ‘primes’”
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Loading required package: primes

Loading required package: rlist

Warning message in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :
“there is no package called ‘rlist’”
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependency ‘XML’


Loading required package: rlist

Loading required package: yaml

Loading required package: lightgbm

Warning message in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :
“there is no package called ‘lightgbm’”
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Loading required package: lightgbm

### 2.2.3 Definicion de Parametros

aqui debe cargar SU semilla primigenia
<br>recuerde cambiar el numero de experimento en cada corrida nueva

In [ ]:
PARAM <- list()
PARAM$experimento <- "5940-3"

PARAM$semilla_primigenia <- 368521

In [ ]:
PARAM$kaggle$competencia <- "data-mining-inicial-2026-a"
PARAM$kaggle$cortes <- seq(9000, 12000, by= 500)

In [ ]:
# un undersampling de 0.1  toma solo el 10% de los CONTINUA
# undersampling de 1.0  implica tomar TODOS los datos

PARAM$trainingstrategy$undersampling <- 0.5

In [ ]:
# Parametros LightGBM

PARAM$hyperparametertuning$xval_folds <- 5

# parametros fijos del LightGBM que se pisaran con la parte variable de la BO
PARAM$lgbm$param_fijos <-  list(
  boosting= "gbdt", # puede ir  dart  , ni pruebe random_forest
  objective= "binary",
  metric= "auc",
  first_metric_only= FALSE,
  boost_from_average= TRUE,
  feature_pre_filter= FALSE,
  force_row_wise= TRUE, # para reducir warnings
  verbosity= -100,

  seed= PARAM$semilla_primigenia,

  max_depth= -1L, # -1 significa no limitar,  por ahora lo dejo fijo
  min_gain_to_split= 0, # min_gain_to_split >= 0
  min_sum_hessian_in_leaf= 0.001, #  min_sum_hessian_in_leaf >= 0.0
  lambda_l1= 0.0, # lambda_l1 >= 0.0
  lambda_l2= 0.0, # lambda_l2 >= 0.0
  max_bin= 31L, # lo debo dejar fijo, no participa de la BO

  bagging_fraction= 1.0, # 0.0 < bagging_fraction <= 1.0
  pos_bagging_fraction= 1.0, # 0.0 < pos_bagging_fraction <= 1.0
  neg_bagging_fraction= 1.0, # 0.0 < neg_bagging_fraction <= 1.0
  is_unbalance= FALSE, #
  scale_pos_weight= 1.0, # scale_pos_weight > 0.0

  drop_rate= 0.1, # 0.0 < neg_bagging_fraction <= 1.0
  max_drop= 50, # <=0 means no limit
  skip_drop= 0.5, # 0.0 <= skip_drop <= 1.0

  extra_trees= FALSE,

  num_iterations= 100,
  learning_rate= 0.10,  # >=0
  feature_fraction= 1.0, # 0 < ff <= 1.0
  num_leaves= 32, # integer >= 2
  min_data_in_leaf= 20 # integer >= 0
)

### 2.2.4  Preprocesamiento

In [ ]:
# carpeta de trabajo

setwd("/content/buckets/b1/exp")
experimento_folder <- paste0("HT", PARAM$experimento)
dir.create(experimento_folder, showWarnings=FALSE)
setwd( paste0("/content/buckets/b1/exp/", experimento_folder ))

In [ ]:
# lectura del dataset

dataset <- fread("/content/datasets/dataset_pequeno.csv")

In [ ]:
dataset_train <- dataset[foto_mes %in% c(202107)]

In [ ]:
# paso la clase a binaria que tome valores {0,1}  enteros
#  BAJA+1 y BAJA+2  son  1,   CONTINUA es 0

dataset_train[,
  clase01 := ifelse(clase_ternaria %in% c("BAJA+2","BAJA+1"), 1L, 0L)
]

In [ ]:
# defino los datos que forma parte del training
# aqui se hace el undersampling de los CONTINUA
# notar que para esto utilizo la SEGUNDA semilla

set.seed(PARAM$semilla_primigenia, kind = "L'Ecuyer-CMRG")
dataset_train[, azar := runif(nrow(dataset_train))]
dataset_train[, training := 0L]

dataset_train[
  foto_mes %in% c(202107) &
    (azar <= PARAM$trainingstrategy$undersampling | clase_ternaria %in% c("BAJA+1", "BAJA+2")),
  training := 1L
]

In [ ]:
# los campos que se van a utilizar

campos_buenos <- setdiff(
  colnames(dataset_train),
  c("clase_ternaria", "clase01", "azar", "training")
)

In [ ]:
# dejo los datos en el formato que necesita LightGBM

dtrain <- lgb.Dataset(
  data= data.matrix(dataset_train[training == 1L, campos_buenos, with= FALSE]),
  label= dataset_train[training == 1L, clase01],
  free_raw_data= FALSE
)

nrow(dtrain)
ncol(dtrain)

[1] 83284

[1] 154

2.2.5 Configuracion del Grid Search

In [ ]:
# En el argumento x llegan los parmaetros de LightGBM
#  devuelve la AUC en cross validation del modelo entrenado

Estimar_AUC_lightgbm <- function(x) {

  # x pisa (o agrega) a param_fijos
  param_completo <- modifyList(PARAM$lgbm$param_fijos, x)

  # entreno LightGBM
  modelocv <- lgb.cv(
    data= dtrain,
    nfold= PARAM$hyperparametertuning$xval_folds,
    stratified= TRUE,
    param= param_completo
  )

  # obtengo la ganancia
  AUC <- modelocv$best_score

  # hago espacio en la memoria
  rm(modelocv)
  gc(full= TRUE, verbose= FALSE)

  message(format(Sys.time(), "%a %b %d %X %Y  "),
    toString(x),
    " AUC ", AUC
  )

  return(AUC)
}

In [ ]:
# lo que sigue a continuacion es una forma alternativa a los loops anidados
# creo una tabla con el producto cartesiano de los vectores
tb_nueva <- CJ(
  num_iterations= c(100, 500, 1000),
  learning_rate= c( 0.02, 0.05, 0.1),
  num_leaves= c(10, 50, 100, 500)
)

In [ ]:
# veo que tiene la tabla antes de procesar
tb_nueva

   num_iterations learning_rate num_leaves
1   100           0.02           10
2   100           0.02           50
3   100           0.02          100
4   100           0.02          500
5   100           0.05           10
6   100           0.05           50
7   100           0.05          100
8   100           0.05          500
9   100           0.10           10
10  100           0.10           50
11  100           0.10          100
12  100           0.10          500
13  500           0.02           10
14  500           0.02           50
15  500           0.02          100
16  500           0.02          500
17  500           0.05           10
18  500           0.05           50
19  500           0.05          100
20  500           0.05          500
21  500           0.10           10
22  500           0.10           50
23  500           0.10          100
24  500           0.10          500
25 1000           0.02           10
26 1000           0.02           50
27 1000           0.02          100
28 1000           0.02          500
29 1000           0.05           10
30 1000           0.05           50
31 1000           0.05          100
32 1000           0.05          500
33 1000           0.10           10
34 1000           0.10           50
35 1000           0.10          100
36 1000           0.10          500

In [ ]:
# registro a registro calculo la AUC
tb_nueva[, AUC:= Estimar_AUC_lightgbm( list(.SD)),
  by=1:nrow(tb_nueva) ]

Wed Jun 24 10:49:22 PM 2026  list(num_iterations = 100, learning_rate = 0.02, num_leaves = 10) AUC 0.925466168129535

Wed Jun 24 10:49:44 PM 2026  list(num_iterations = 100, learning_rate = 0.02, num_leaves = 50) AUC 0.926671416062192

Wed Jun 24 10:50:06 PM 2026  list(num_iterations = 100, learning_rate = 0.02, num_leaves = 100) AUC 0.926272173036097

Wed Jun 24 10:50:23 PM 2026  list(num_iterations = 100, learning_rate = 0.02, num_leaves = 500) AUC 0.925923298330186

Wed Jun 24 10:50:41 PM 2026  list(num_iterations = 100, learning_rate = 0.05, num_leaves = 10) AUC 0.925407662478503

Wed Jun 24 10:50:59 PM 2026  list(num_iterations = 100, learning_rate = 0.05, num_leaves = 50) AUC 0.926546677355803

Wed Jun 24 10:51:20 PM 2026  list(num_iterations = 100, learning_rate = 0.05, num_leaves = 100) AUC 0.926157780119311

Wed Jun 24 10:51:38 PM 2026  list(num_iterations = 100, learning_rate = 0.05, num_leaves = 500) AUC 0.926061272721663

Wed Jun 24 10:51:56 PM 2026  list(num_iterations = 100, learning_rate = 0.1, num_leaves = 10) AUC 0.927058533466519

Wed Jun 24 10:52:13 PM 2026  list(num_iterations = 100, learning_rate = 0.1, num_leaves = 50) AUC 0.925694509011753

Wed Jun 24 10:52:35 PM 2026  list(num_iterations = 100, learning_rate = 0.1, num_leaves = 100) AUC 0.926387302606714

Wed Jun 24 10:52:52 PM 2026  list(num_iterations = 100, learning_rate = 0.1, num_leaves = 500) AUC 0.926009206010255

Wed Jun 24 10:53:10 PM 2026  list(num_iterations = 500, learning_rate = 0.02, num_leaves = 10) AUC 0.924695298253718

Wed Jun 24 10:53:28 PM 2026  list(num_iterations = 500, learning_rate = 0.02, num_leaves = 50) AUC 0.925579742324713

Wed Jun 24 10:53:49 PM 2026  list(num_iterations = 500, learning_rate = 0.02, num_leaves = 100) AUC 0.926501151672765

Wed Jun 24 10:54:07 PM 2026  list(num_iterations = 500, learning_rate = 0.02, num_leaves = 500) AUC 0.926143690364422

Wed Jun 24 10:54:25 PM 2026  list(num_iterations = 500, learning_rate = 0.05, num_leaves = 10) AUC 0.926153961453623

Wed Jun 24 10:54:43 PM 2026  list(num_iterations = 500, learning_rate = 0.05, num_leaves = 50) AUC 0.926765215759629

Wed Jun 24 10:55:04 PM 2026  list(num_iterations = 500, learning_rate = 0.05, num_leaves = 100) AUC 0.927217426405854

Wed Jun 24 10:55:23 PM 2026  list(num_iterations = 500, learning_rate = 0.05, num_leaves = 500) AUC 0.925289219264099

Wed Jun 24 10:55:42 PM 2026  list(num_iterations = 500, learning_rate = 0.1, num_leaves = 10) AUC 0.925217668473605

Wed Jun 24 10:56:04 PM 2026  list(num_iterations = 500, learning_rate = 0.1, num_leaves = 50) AUC 0.92686334166693

Wed Jun 24 10:56:22 PM 2026  list(num_iterations = 500, learning_rate = 0.1, num_leaves = 100) AUC 0.925740566477463

Wed Jun 24 10:56:40 PM 2026  list(num_iterations = 500, learning_rate = 0.1, num_leaves = 500) AUC 0.925648318528829

Wed Jun 24 10:56:58 PM 2026  list(num_iterations = 1000, learning_rate = 0.02, num_leaves = 10) AUC 0.927045308541882

Wed Jun 24 10:57:19 PM 2026  list(num_iterations = 1000, learning_rate = 0.02, num_leaves = 50) AUC 0.927928140534891

Wed Jun 24 10:57:37 PM 2026  list(num_iterations = 1000, learning_rate = 0.02, num_leaves = 100) AUC 0.925890066909019

Wed Jun 24 10:57:55 PM 2026  list(num_iterations = 1000, learning_rate = 0.02, num_leaves = 500) AUC 0.92789516190608

Wed Jun 24 10:58:13 PM 2026  list(num_iterations = 1000, learning_rate = 0.05, num_leaves = 10) AUC 0.925055681534551

Wed Jun 24 10:58:34 PM 2026  list(num_iterations = 1000, learning_rate = 0.05, num_leaves = 50) AUC 0.926384258892094

Wed Jun 24 10:58:52 PM 2026  list(num_iterations = 1000, learning_rate = 0.05, num_leaves = 100) AUC 0.925605221941261

Wed Jun 24 10:59:09 PM 2026  list(num_iterations = 1000, learning_rate = 0.05, num_leaves = 500) AUC 0.926100100228393

Wed Jun 24 10:59:27 PM 2026  list(num_iterations = 1000, learning_rate = 0.1, num_leaves = 10) AUC 0.926704599846194

Wed Jun 24 10:59:48 PM 2026  list(num_iterations = 1000, learning_rate = 0.1, num_leaves = 50) AUC 0.927853416512879

Wed Jun 24 11:00:06 PM 2026  list(num_iterations = 1000, learning_rate = 0.1, num_leaves = 100) AUC 0.926315160417895

Wed Jun 24 11:00:24 PM 2026  list(num_iterations = 1000, learning_rate = 0.1, num_leaves = 500) AUC 0.925870120279929

In [ ]:
# veo que tiene la tabla DESPUES de procesar
tb_nueva

   num_iterations learning_rate num_leaves AUC
1   100           0.02           10        0.9254662
2   100           0.02           50        0.9266714
3   100           0.02          100        0.9262722
4   100           0.02          500        0.9259233
5   100           0.05           10        0.9254077
6   100           0.05           50        0.9265467
7   100           0.05          100        0.9261578
8   100           0.05          500        0.9260613
9   100           0.10           10        0.9270585
10  100           0.10           50        0.9256945
11  100           0.10          100        0.9263873
12  100           0.10          500        0.9260092
13  500           0.02           10        0.9246953
14  500           0.02           50        0.9255797
15  500           0.02          100        0.9265012
16  500           0.02          500        0.9261437
17  500           0.05           10        0.9261540
18  500           0.05           50        0.9267652
19  500           0.05          100        0.9272174
20  500           0.05          500        0.9252892
21  500           0.10           10        0.9252177
22  500           0.10           50        0.9268633
23  500           0.10          100        0.9257406
24  500           0.10          500        0.9256483
25 1000           0.02           10        0.9270453
26 1000           0.02           50        0.9279281
27 1000           0.02          100        0.9258901
28 1000           0.02          500        0.9278952
29 1000           0.05           10        0.9250557
30 1000           0.05           50        0.9263843
31 1000           0.05          100        0.9256052
32 1000           0.05          500        0.9261001
33 1000           0.10           10        0.9267046
34 1000           0.10           50        0.9278534
35 1000           0.10          100        0.9263152
36 1000           0.10          500        0.9258701

In [ ]:
fwrite( tb_nueva,
  file= "tb_grid_serach_01.txt",
  sep="\t",
  append= TRUE
)

In [ ]:
setorder( tb_nueva, -AUC)
PARAM$out$lgbm$AUC <- tb_nueva[1, AUC]
PARAM$out$lgbm$mejores_hiperparametros <- as.list( tb_nueva[1] )
PARAM$out$lgbm$mejores_hiperparametros$AUC <- NULL
PARAM$out$lgbm$mejores_hiperparametros

$num_iterations
[1] 1000

$learning_rate
[1] 0.02

$num_leaves
[1] 50

In [ ]:
write_yaml( PARAM, file="PARAM.yml")

## 2.3  Produccion

### Final Training
Construyo el modelo final, que es uno solo, no hace ningun tipo de particion < training, validation, testing>]

In [ ]:
setwd("/content/buckets/b1/exp")
experimento <- paste0("exp", PARAM$experimento)
dir.create(experimento, showWarnings= FALSE)
setwd( paste0("/content/buckets/b1/exp/", experimento ))

#### Final Training Dataset

Aqui esta la gran decision de en qué meses hago el Final Training
<br> debo utilizar los mejores hiperparámetros que encontré en la optimización de hiperparametros

In [ ]:
# clase01
dataset[, clase01 := ifelse(clase_ternaria %in% c("BAJA+1", "BAJA+2"), 1L, 0L)]

In [ ]:
dataset_train <- dataset[foto_mes %in% c(202107)]

In [ ]:
# dejo los datos en el formato que necesita LightGBM

dtrain <- lgb.Dataset(
  data= data.matrix(dataset_train[, campos_buenos, with= FALSE]),
  label= dataset_train[, clase01]
)

#### Final Training Hyperparameters

In [ ]:
param_final <- modifyList(PARAM$lgbm$param_fijos,
  PARAM$out$lgbm$mejores_hiperparametros)

param_final

$boosting
[1] "gbdt"

$objective
[1] "binary"

$metric
[1] "auc"

$first_metric_only
[1] FALSE

$boost_from_average
[1] TRUE

$feature_pre_filter
[1] FALSE

$force_row_wise
[1] TRUE

$verbosity
[1] -100

$seed
[1] 368521

$max_depth
[1] -1

$min_gain_to_split
[1] 0

$min_sum_hessian_in_leaf
[1] 0.001

$lambda_l1
[1] 0

$lambda_l2
[1] 0

$max_bin
[1] 31

$bagging_fraction
[1] 1

$pos_bagging_fraction
[1] 1

$neg_bagging_fraction
[1] 1

$is_unbalance
[1] FALSE

$scale_pos_weight
[1] 1

$drop_rate
[1] 0.1

$max_drop
[1] 50

$skip_drop
[1] 0.5

$extra_trees
[1] FALSE

$num_iterations
[1] 1000

$learning_rate
[1] 0.02

$feature_fraction
[1] 1

$num_leaves
[1] 50

$min_data_in_leaf
[1] 20

#### Training
Genero el modelo final, siempre sobre TODOS los datos de  final_train, sin hacer ningun tipo de undersampling de la clase mayoritaria

In [ ]:
# este punto es muy SUTIL  y será revisado en la Clase 05

param_normalizado <- copy(param_final)
param_normalizado$min_data_in_leaf <-  round(param_final$min_data_in_leaf / PARAM$trainingstrategy$undersampling)

In [ ]:
  # entreno LightGBM

  modelo_final <- lgb.train(
    data= dtrain,
    param= param_normalizado
  )

In [ ]:
# ahora imprimo la importancia de variables

tb_importancia <- as.data.table(lgb.importance(modelo_final))
archivo_importancia <- "impo.txt"

fwrite(tb_importancia,
  file= archivo_importancia,
  sep= "\t"
)

In [ ]:
# grabo a disco el modelo en un formato para seres humanos ... ponele ...

lgb.save(modelo_final, "modelo.txt" )

### Scoring

Aplico el modelo final a los datos del futuro

In [ ]:
# aplico el modelo a los datos sin clase
dfuture <- dataset[foto_mes == 202109]

# aplico el modelo a los datos nuevos
prediccion <- predict(
  modelo_final,
  data.matrix(dfuture[, campos_buenos, with= FALSE])
)

#### Tabla Prediccion

In [ ]:
# tabla de prediccion

tb_prediccion <- dfuture[, list(numero_de_cliente)]
tb_prediccion[, prob := prediccion ]

# grabo las probabilidad del modelo
fwrite(tb_prediccion,
  file= "prediccion.txt",
  sep= "\t"
)

Kaggle Competition Submit

In [ ]:
# genero archivos con los  "envios" mejores
# suba TODOS los archivos a Kaggle

# ordeno por probabilidad descendente
setorder(tb_prediccion, -prob)

dir.create("kaggle")

for (envios in PARAM$kaggle$cortes) {

  tb_prediccion[, Predicted := 0L] # seteo inicial a 0
  tb_prediccion[1:envios, Predicted := 1L] # marclo los primeros

  archivo_kaggle <- paste0("./kaggle/KA", PARAM$experimento, "_", envios, ".csv")

  # grabo el archivo
  fwrite(tb_prediccion[, list(numero_de_cliente, Predicted)],
    file= archivo_kaggle,
    sep= ","
  )

  # subida a Kaggle, armo la linea de comando
  comando <- "kaggle competitions submit"
  competencia <- paste("-c", PARAM$kaggle$competencia)
  arch <- paste( "-f", archivo_kaggle)

  mensaje <- paste0("-m 'envios=", envios,
  "  semilla=", PARAM$semilla_primigenia,
    "'" )

  linea <- paste( comando, competencia, arch, mensaje)

  salida <- system(linea, intern=TRUE) # el submit a Kaggle
  cat(salida, "\n")
  Sys.sleep(45)
}

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2) Successfully submitted to Data Mining, Inicial 2026 A
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2) Successfully submitted to Data Mining, Inicial 2026 A
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2) Successfully submitted to Data Mining, Inicial 2026 A
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2) Successfully submitted to Data Mining, Inicial 2026 A
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2) Successfully submitted to Data Mining, Inicial 2026 A
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2) Successfully submitted to Data Mining, Inicial 2026 A
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2) Successfully submitted to Data Mining, Inicial 2026 A

In [ ]:
write_yaml( PARAM, file="PARAM.yml")

In [ ]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Wed Jun 24 11:07:41 PM 2026"

Finalmente usted deberá cargar el resultado de su corrida en la Google Sheet Colaborativa,  hoja **TareaHogar-04**
<br> Siéntase libre de agregar las columnas que hagan falta a la planilla

Seguramente usted realice varias corridas de este script con distintos conjuntos de hiperparámetros, siempre cambiandole el nombre al script  y también cambiando el nombre del experimento,  deberá TODAS esas corridas en distintas lineas de la  Google Sheet Colaborativa, hoja **TareaHogar-04**

Siéntase libre de agregar columnas a la hoja **TareaHogar-04**  en caso de ser necesario.